---
- name: To create docker image and push to dockerhub
  hosts: localhost
  connection: local
  tasks:
    - name: Login to Dockerhub 
      command: docker login -u viswar4 -p {{ DOCKER_HUB_CREDENTIALS }}
    - name: Build and Push Docker Image
      docker_image:
        name: viswar4/capstone1:{{ DOCKER_IMAGE_TAG }}
        build:
          path: "{{ WORKSPACE }}"
        source: build
        push: true
    - name: Logout out of Dockerhub
      docker_login:
        state: absent
      